modLoader="javafml"
loaderVersion="[47,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="reverie"
version="1.0.0"
displayName="REVERIE"
displayURL="https://rickrolled.net"
credits="Closed Alpha"
authors="eris"
description="ALPHA"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.reverie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration